[Post] Refactoring sn-redux store
SenseNet/sensenet.github.io pull request #110
Opened 2017-09-19 09:52 UTC by herflis

2017-09-19 11:30 UTC, gallayl approved these changes

2017-09-19 12:22 UTC, tusmester approved these changes

2017-09-20 05:50 UTC, borsi requested changes
I noticed a minor grammatical error in the beginning, but otherwise, cool 👍

2017-09-20 05:50 UTC, borsi commented on _drafts/2017-09-20-refactoring-sensenet-redux-store.md
> +In the last few months I've read a couple of posts about the Redux store of Twitter and I thought if it was interesting to dig into their state tree it will be useful to write an article like this ab
were not only guide us... -> were not only guiding us in analyzing...
the tense is not right here imho

2017-09-20 10:11 UTC, borsi approved these changes

2017-09-20 10:15 UTC, merged