Posts/in memory testing
SenseNet/sensenet.github.io pull request #118
Opened 2017-10-22 12:22 UTC by tusmester

Post about how we approached in-memory testing.

2017-10-25 11:26 UTC, iviczl commented on _drafts/2017-11-01-in-memory-testing.md
> +That is not how a modern test environment should work, because of many reasons: speed, maintainability, flexibility.
This snippet would be more appropriate, if you count to three only:
...because of the following reasons: ...

2017-10-25 18:59 UTC, gallayl approved these changes

2017-10-27 08:28 UTC, borsi requested changes

2017-10-27 08:28 UTC, borsi commented on _drafts/2017-11-01-in-memory-testing.md
> +![Testing an ECM product](/img/posts/inmemory_database.png)
not sure if this url's valid.

2017-10-27 08:28 UTC, borsi commented on _drafts/2017-11-01-in-memory-testing.md
> +We started to experiment with simulating the database in memory and implementing load and save operations on top of that. It turned out that @kavics was able to construct an in-memory db in just a fe
I'm not sure if jekyll will link to @kavics here. You may need to explicitly reference his profile: https://github.com/kavics

2017-10-27 12:16 UTC, tusmester commented on _drafts/2017-11-01-in-memory-testing.md
> +![Testing an ECM product](/img/posts/inmemory_database.png)
I think it is. There is no leading "../" in image links in other posts.

2017-10-27 12:27 UTC, borsi approved these changes

2017-10-27 12:28 UTC, merged