[Post] Product goals for 2018 Q2
SenseNet/sensenet.github.io pull request #143
Opened 2018-01-30 16:01 UTC by herflis

2018-04-05 21:31 UTC, tusmester requested changes
This is a very optimistic goal list :).

2018-04-05 21:31 UTC, tusmester commented on _drafts/2018-03-01-q2-goals.md
> +#### Azure SQL & AD
Not sure this will happen in the short term, I think we should remove this section for now.

2018-04-05 21:31 UTC, tusmester commented on _drafts/2018-03-01-q2-goals.md
> +We would like to understand how people really use sensenet and make it more simple and easy to understand, so you’ll find every button, controls and other elements at the right place, you won’t need
'search' for them

2018-04-05 21:31 UTC, tusmester commented on _drafts/2018-03-01-q2-goals.md
> +The core concept of this revamp is to introduce a new simplified user interface with only the required features and separate it from the content explorer.
...to introduce the foundations of a.... OR
...create the first building blocks of a....OR
...start working on a new simplified etc...

2018-04-05 21:31 UTC, tusmester commented on _drafts/2018-03-01-q2-goals.md
> +### Dynamic Content Type editing
This is only a discussion thread about custom metadata, I wouldn't mention this yet, especially not using 'near' and 'without coding'. I think we should remove this section too, it is too early to list this.

2018-04-12 11:07 UTC, gallayl approved these changes

2018-04-12 11:58 UTC, tusmester approved these changes

2018-05-09 10:04 UTC, merged