[Post] 2018 Q1 results
SenseNet/sensenet.github.io pull request #178
Opened 2018-04-04 07:31 UTC by herflis

2018-04-19 18:15 UTC, tusmester requested changes

2018-04-19 18:15 UTC, tusmester commented on _drafts/2018-04-18-q1-results.md
> +title: "Hangzatos cím"
This title - although it is very hangzatos - is not totally appropriate.

2018-04-19 18:15 UTC, tusmester commented on _drafts/2018-04-18-q1-results.md
> +The new tests are intended to test small pieces of the source code without depending on other parts, therefore we can quickly locate errors without reviewing the whole code. Another important point i
A few words of a conclusion, a closure would be nice, for example a hint that there is another post coming about the next quarter.

2018-04-19 18:22 UTC, herflis commented on _drafts/2018-04-18-q1-results.md
> +title: "Hangzatos cím"
it was a trap :D

2018-05-02 08:31 UTC, tusmester approved these changes

2018-05-02 09:05 UTC, merged