[Post] Docviewer
SenseNet/sensenet.github.io pull request #227
Opened 2018-08-14 08:45 UTC by CsabaPeter

2018-08-14 08:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SenseNet/sensenet.github.io?pullRequest=227) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SenseNet/sensenet.github.io?pullRequest=227) before we can accept your contribution.<br/><hr/>**Csaba Péter** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SenseNet/sensenet.github.io?pullRequest=227) it.</sub>

2018-08-15 11:01 UTC, herflis approved these changes

2018-08-16 06:58 UTC, huszerlbence requested changes
Great article, it's interesting to see behind the scenes. I added a few comments (some of them are typos and there are some suggestions as well).

2018-08-16 06:58 UTC, huszerlbence commented on _drafts/2018-08-14-docviewer.md
> +My work began with sitting down with the team and discussing what our main goal was (simplify the app and get rid of unused features). After that I started looking around for best practices like how
Maybe: My work began by sitting down...?

2018-08-16 06:58 UTC, huszerlbence commented on _drafts/2018-08-14-docviewer.md
> +After clarifying the main path that we should take, I conducted a few user interviews (six to be exact) to find out what people mainly looknig for when they open a document viewer. After the intervie
looknig --> looking

in this context, "among" means one of the team members was the winner.
Maybe: clear winner selected/chosen by the team...

2018-08-16 06:58 UTC, huszerlbence commented on _drafts/2018-08-14-docviewer.md
> +After the wireframing I made high fidelity prototypes in light and dark mode. For the high fidelity prototype I used [Sketch](https://www.sketchapp.com/) and followed [Material Design](https://materi
For the high fidelity prototype --> For this

2018-08-16 06:58 UTC, huszerlbence commented on _drafts/2018-08-14-docviewer.md
> +3: Go to gage 2 and 3 then go back to the top of the page
gage  --> page

2018-08-16 06:58 UTC, huszerlbence commented on _drafts/2018-08-14-docviewer.md
> +I updated my design after the first set of user tests and I conducted a second round test with the same participants. The results were much better this time and eveyone made through the tests without
this time and eveyone --> this time and everyone

maybe to explain the order of the button you could import a screenshot of the navbar (before & after)
--> I also changed the order of the icons as following:

2018-08-16 08:37 UTC, huszerlbence approved these changes

2018-08-22 08:55 UTC, merged