Docs/security
SenseNet/sensenet.github.io pull request #242
Opened 2018-11-23 14:30 UTC by tusmester

Add sharing and security-related documentation.

2018-11-26 10:59 UTC, herflis approved these changes

2018-12-07 12:38 UTC, zoltanbedi approved these changes

2019-01-11 11:14 UTC, kultsar requested changes

2019-01-11 11:14 UTC, kultsar commented on _docs/sharing.md
> +You can switch ON or OFF the feature or customize the notification emails using the *Sharing* settings.
```suggestion
You can switch ON or OFF notifications or customize the notification emails using the *Sharing* settings.
```

2019-01-11 11:14 UTC, kultsar commented on _docs/sharing.md
> +If there are *private* sharing records with this email and *no identity*, we will give explicit permissions for the new user on that content. This is to make sure that if a user registers to access a
```suggestion
If there are *private* sharing records with this email address and *no identity*, we will give explicit permissions for the new user on that content. This is to make sure that if a user registers to access a content that was shared with them privately, they get a seamless user experience.
```

2019-01-23 15:23 UTC, kultsar approved these changes

2019-01-23 15:39 UTC, merged