initial commit
SenseNet/sensenet.github.io pull request #253
Opened 2019-04-02 11:06 UTC by gallayl

2019-04-02 11:37 UTC, herflis commented on _updates/2019-04-04-april-2019.md
> + - Project references changes
```suggestion
 - Project reference changes
```

2019-04-02 12:17 UTC, zoltanbedi approved these changes

2019-04-02 12:22 UTC, herflis commented on _updates/2019-04-04-april-2019.md
> + - Move defaultitemtemplate to a separate component
```suggestion
```

2019-04-02 12:22 UTC, herflis commented on _updates/2019-04-04-april-2019.md
> + - feat: Display add reference row when value is empty after removing the last ite
```suggestion
```

2019-04-03 09:59 UTC, kultsar requested changes

2019-04-03 09:59 UTC, kultsar commented on _updates/2019-04-04-april-2019.md
> + - Added Groups page
- Added Groups edit metadata
- Added Groups list
- Added User edit metadata

2019-04-03 10:11 UTC, merged