Updates of release 2019-05
SenseNet/sensenet.github.io pull request #254
Opened 2019-04-30 13:14 UTC by herflis

2019-04-30 13:30 UTC, B3zo0 commented on _updates/2019-05-02-may-2019.md
> +- Passing request inits to fetch
There was a breaking change in client core. see https://github.com/SenseNet/sn-client/pull/152

2019-04-30 13:30 UTC, B3zo0 commented on _updates/2019-05-02-may-2019.md
> +- Move assets outside of src
```suggestion
```
in this package the assets were completely removed.

2019-04-30 13:30 UTC, B3zo0 commented on _updates/2019-05-02-may-2019.md
> +### [@sensenet/list-controls-react@1.4.0](https://github.com/SenseNet/sn-client/releases/tag/%40sensenet%2Flist-controls-react%401.4.0)
This should be pickers react.

2019-05-02 08:58 UTC, gallayl requested changes

2019-05-02 08:58 UTC, gallayl commented on _updates/2019-05-02-may-2019.md
> +
```suggestion
 - refactored upload and made it available in the repository object

```

2019-05-02 08:58 UTC, gallayl commented on _updates/2019-05-02-may-2019.md
> +- From redux to context, added save & cancel button for text editor
```suggestion
- Moved editor-related state from redux to context, added save & cancel button for text editor
```

2019-05-02 08:59 UTC, merged