Release docs for the second release of 2019 June
SenseNet/sensenet.github.io pull request #256
Opened 2019-06-24 08:57 UTC by gallayl

2019-06-25 09:17 UTC, herflis commented on _updates/2019-06-24-june_2-2019.md
> + - fixed sanbox attribute's value
```suggestion
 - fixed sandbox attribute's value
```

2019-06-25 09:17 UTC, herflis commented on _updates/2019-06-24-june_2-2019.md
> +### sn-dms-demo@
```suggestion
### sn-dms-demo
```

2019-06-25 09:18 UTC, herflis commented on _updates/2019-06-24-june_2-2019.md
> +### @sensenet/sn-app@
```suggestion
### @sensenet/sn-app
```

2019-06-26 09:32 UTC, zoltanbedi approved these changes
📄

2019-06-26 09:32 UTC, B3zo0 commented on _updates/2019-06-24-june_2-2019.md
> + - varioius search fixes
```suggestion
 - various search fixes
```

2019-06-26 09:43 UTC, tusmester requested changes

2019-06-26 09:43 UTC, tusmester commented on _updates/2019-06-24-june_2-2019.md
> +## Mononorepo changes
```suggestion
## Monorepo changes
```

2019-06-26 10:21 UTC, merged