Docs/drawer customization
SenseNet/sensenet.github.io pull request #410
Opened 2019-11-22 14:54 UTC by B3zo0

2019-11-22 15:09 UTC, herflis commented on _docs/admin-ui/drawer-customization-in-general.md
> +The Drawer component is the left side navigation menu. It lets you access the [personal settings](/docs/admin-ui/personal-settings), [setup](/docs/admin-ui/setup), [version-info](/docs/admin-ui/versi
```suggestion
The Drawer component is the left side navigation menu. It lets you access the [personal settings](/docs/admin-ui/personal-settings), [setup](/docs/admin-ui/setup), [version-info](/docs/admin-ui/version-info) and more other menupoints.
```

2019-11-22 15:09 UTC, herflis commented on _docs/admin-ui/drawer-customization-in-general.md
> +You can customize the drawer in the [personal settings](/docs/admin-ui/personal-settings). There are 3 options that you can pass to the drawer settings.
```suggestion
You can customize the drawer with the [personal settings](/docs/admin-ui/personal-settings). There are 3 main options that you can pass to the drawer settings.
```

2019-11-22 15:12 UTC, herflis commented on _docs/admin-ui/drawer-customization-in-general.md
> +This it the simplest setting of the drawer. You can enable or disable it. Don't worry if you disabled the drawer and can't find personal settings. You can access it from [Command palette](/docs/admin
```suggestion
This it the simplest setting that can enable or disable the drawer itself. Don't worry if you disabled the drawer and can't find personal settings. You can access it from the [Command palette](/docs/admin-ui/command-palette) with typing in *personal settings* and pressing enter.
```

2019-11-22 15:13 UTC, herflis commented on _docs/admin-ui/drawer-customization-in-general.md
> +There are 3 possible values for type:
```suggestion
There are 3 possible values for choosing the type of the drawer:
```

2019-11-22 15:13 UTC, herflis commented on _docs/admin-ui/drawer-customization-in-general.md
> +**permanent** - In this mode the drawer is always opened.
```suggestion
**permanent** - In this mode the drawer is always open.
```

2019-11-25 13:07 UTC, herflis commented on _docs/admin-ui/drawer-customization-in-general.md
> +You can customize the drawer with in the [personal settings](/docs/admin-ui/personal-settings). You can set drawer options for multiple devices. For example mobile, tablet, desktop and in general for
```suggestion
You can customize the drawer within the [personal settings](/docs/admin-ui/personal-settings). You can set drawer options for multiple devices. For example mobile, tablet, desktop and in general for default. There are 3 main options:
```

2019-11-25 13:15 UTC, enikonemeth requested changes
@B3zo0 : Pls check, what I mentioned

2019-11-25 13:15 UTC, enikonemeth commented on _docs/admin-ui/drawer-customization-in-general.md
> +**mini-variant** - This can be opened and closed as it is shown above. _This is currently the default setting for desktop mode_
```suggestion
**mini-variant** - This can be opened and closed as it is shown below. _This is currently the default setting for desktop mode_
```

2019-11-25 13:15 UTC, pusztaienike commented on _docs/admin-ui/drawer-customization-in-general.md
> +The `settings` property changes for item types, there are items that doesn't have settings at all.
```suggestion
The `settings` property changes for item types, there are items that don't have settings at all.
```

+ It is a contradiction - with the previous sentence. 
"Every drawer item has 3 properties" <--> "there are items that doesn't have settings at all"

2019-11-25 15:44 UTC, herflis approved these changes
🍖

2019-11-25 16:03 UTC, enikonemeth approved these changes

2019-11-25 16:20 UTC, merged