Add body text of api introduction
SenseNet/sensenet.github.io pull request #418
Opened 2020-01-20 10:32 UTC by herflis

2020-01-28 10:40 UTC, B3zo0 commented on content/docs/api/examples/collection/children/js-snclient.md
> +
```suggestion
<iframe
     src="https://codesandbox.io/embed/elastic-star-cu6l0?expanddevtools=1&fontsize=14&hidenavigation=1&theme=dark"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="elastic-star-cu6l0"
     allow="geolocation; microphone; camera; midi; vr; accelerometer; gyroscope; payment; ambient-light-sensor; encrypted-media; usb"
     sandbox="allow-modals allow-forms allow-popups allow-scripts allow-same-origin"
   ></iframe>
```

2020-01-28 12:17 UTC, enikonemeth commented on content/docs/api/basic-concepts/introduction.md
> +The requested resource can be any content in the repository (since everything is a content in sensenet, it could by really anything) that is permitted for the current user.
```suggestion
The requested resource can be any content in the repository (since everything is a content in sensenet, it could be really anything) that is permitted for the current user. 
```

2020-01-28 12:17 UTC, enikonemeth commented on content/docs/api/basic-concepts/introduction.md
> +Query options are query string parameters a client may specify to control the amount and order of the data that a service returns for the resource identified by the URI. In sensenet there're two type
```suggestion
Query options are query string parameters a client may specify to control the amount and order of the data that a service returns for the resource identified by the URI. In sensenet there're two types of query options available [OData System Query Options](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/) and custom sensenet query options. The OData standard query option's names are prefixed with a "$" character, sensenet query options can be used without prefix.
```

2020-01-28 12:17 UTC, enikonemeth commented on content/docs/api/examples/entry/byPath/js.md
>  ```javascript
```suggestion
async function fetchContent() {
  try {
    const response = await fetch(
      "https://dev.demo.sensenet.com/OData.svc/Root/Content('IT')",
      { credentials: "include" }
    );
    const result = await response.json();
    console.log(result);
  } catch (err) {
    console.log(err);
  }
}
```

2020-01-28 12:17 UTC, enikonemeth commented on content/docs/api/examples/entry/property/js.md
> +```javascript
```suggestion
async function fetchContent() {
  try {
    const response = await fetch(
      "https://dev.demo.sensenet.com/OData.svc/Root/Content('IT')/DisplayName",
      { credentials: "include" }
    );
    const result = await response.json();
    console.log(result);
  } catch (err) {
    console.log(err);
  }
}
```

2020-01-28 12:17 UTC, enikonemeth commented on content/docs/api/examples/collection/children/js.md
> +```javascript
```suggestion
async function fetchContent() {
  try {
    const response = await fetch(
      "https://dev.demo.sensenet.com/OData.svc/Root/Content",
      { credentials: "include" }
    );
    const result = await response.json();
    console.log(result);
  } catch (err) {
    console.log(err);
  }
}
```

2020-01-28 12:17 UTC, enikonemeth commented on content/docs/api/examples/collection/count/js.md
> +```javascript
```suggestion
async function fetchContent() {
  try {
    const response = await fetch(
      "https://dev.demo.sensenet.com/OData.svc/Root/Content/IT/$count",
      { credentials: "include" }
    );
    const result = await response.json();
    console.log(result);
  } catch (err) {
    console.log(err);
  }
}
```

2020-01-28 12:17 UTC, enikonemeth commented on content/docs/api/examples/collection/inlinecount/js.md
> +```javascript
```suggestion
async function fetchContent() {
  try {
    const response = await fetch(
      "https://dev.demo.sensenet.com/OData.svc/Root/Content/IT?$top=3&$skip=4&$inlinecount=allpages",
      { credentials: "include" }
    );
    const result = await response.json();
    console.log(result);
  } catch (err) {
    console.log(err);
  }
}
```

2020-01-28 12:17 UTC, enikonemeth commented on content/docs/api/examples/entry/propertyValue/js.md
> +```javascript
```suggestion
async function fetchContent() {
  try {
    const response = await fetch(
      "https://dev.demo.sensenet.com/OData.svc/Root/Content('IT')/DisplayName/$value",
      { credentials: "include" }
    );
    const result = await response.text();
    console.log(result);
  } catch (err) {
    console.log(err);
  }
}
```

2020-01-28 13:45 UTC, tusmester requested changes
pls review these typo fixes

2020-01-28 13:45 UTC, tusmester commented on content/docs/api/basic-concepts/introduction.md
> +sensenet offers you a rich API allowing you to manage, integrate and deliver content on all type of clients, devices and platforms. This section explains the API structure and main concepts in more d
```suggestion
sensenet offers you a rich API allowing you to manage, integrate and deliver content on all types of clients, devices and platforms. This section explains the API structure and main concepts in more depth. 
```

2020-01-28 13:45 UTC, tusmester commented on content/docs/api/basic-concepts/introduction.md
> +Query options are query string parameters a client may specify to control the amount and order of the data that a service returns for the resource identified by the URI. In sensenet there're two type
```suggestion
Query options are query string parameters a client may specify to control the amount and order of the data that a service returns for the resource identified by the URI. In sensenet there're two types of query options available [OData System Query Options](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/) and custom sensenet query options. The OData standard query options' names are prefixed with a "$" character, sensenet query options should be used without a prefix.
```

2020-01-28 13:45 UTC, tusmester commented on content/docs/api/basic-concepts/introduction.md
> +| [$expand](/select-expand#expand) | allows you to identify related entries with a single URI such that a graph of entries could be retrieved with a single HTTP request (e.g. by creator user) |
```suggestion
| [$expand](/select-expand#expand) | allows you to identify related entries with a single URI such that a graph of entries could be retrieved with a single HTTP request (e.g. creator user or any other related content) |
```

2020-01-28 13:45 UTC, tusmester commented on content/docs/api/basic-concepts/introduction.md
> +| [$inlinecount](/collection#inlinecount) | controls the `__count` property that can be found every collection response |
```suggestion
| [$inlinecount](/collection#inlinecount) | controls the `__count` property that can be found in every collection response |
```

2020-01-28 13:45 UTC, tusmester commented on content/docs/api/basic-concepts/introduction.md
> +| [query](/search-filter/) | helps to get filtered collection of entities with sensenet Content Query |
```suggestion
| [query](/search-filter/) | filter the result collection using sensenet Content Query |
```

2020-01-28 13:45 UTC, tusmester commented on content/docs/api/basic-concepts/introduction.md
> +| DELETE | [deleting an entity](). The URL determines the entity that will be deleted. Always only one entity (and its children) will be deleted. |
```suggestion
| DELETE | [deleting an entity](). The entity (defined in the URL) and its children will be deleted. |
```

2020-01-28 13:45 UTC, tusmester commented on content/docs/api/basic-concepts/collection.md
> +The requested (parent) resource can be any content in the repository that is permitted for the current user. The resource may be addressed with a content's Path. It returns with a list of entities an
```suggestion
The requested (parent) resource can be any content in the repository that is permitted for the current user. The resource may be addressed with a content's Path. It returns a list of child entities and all their properties.
```

2020-01-28 13:45 UTC, tusmester commented on content/docs/api/basic-concepts/collection.md
> +If the requested (parent) resource is not found, the server returns with a 404 Error status code.
```suggestion
If the requested (parent) resource is not found, the server returns a 404 Error status code.
```

2020-01-28 13:45 UTC, tusmester commented on content/docs/api/basic-concepts/collection.md
> +Service path followed by the site relative path of the container returns child content of the requested parent as a collection.
```suggestion
Service path followed by the path of the container returns child content of the requested parent as a collection.
```

2020-01-28 13:45 UTC, tusmester commented on content/docs/api/basic-concepts/collection.md
>  This returns with a raw integer value.
```suggestion
This returns a raw integer value.
```

2020-01-28 14:25 UTC, tusmester requested changes
added a few sample lines

2020-01-28 14:25 UTC, tusmester commented on content/docs/api/examples/entry/byId/dotnet.md
> +
```suggestion
await Content.LoadAsync(1284);
```

2020-01-28 14:25 UTC, tusmester commented on content/docs/api/examples/entry/byPath/dotnet.md
> +
```suggestion
await Content.LoadAsync("/Root/Content/IT");
```

2020-01-28 14:25 UTC, tusmester commented on content/docs/api/examples/entry/property/dotnet.md
> +
```suggestion
await RESTCaller.GetResponseStringAsync("/Root/Content/IT", "DisplayName");
```

2020-01-28 14:48 UTC, B3zo0 commented on content/docs/api/examples/collection/count/js-snclient.md
> +
```suggestion
import { Repository } from "@sensenet/client-core";

const repository = new Repository({
  repositoryUrl: "https://dev.demo.sensenet.com"
});

try {
  const result = await repository.loadCollection({
    path: "/Root/Content/IT/$count"
  });
  console.log(result);
} catch (error) {
  console.log(error);
}
```

2020-01-28 14:55 UTC, B3zo0 commented on content/docs/api/examples/collection/inlinecount/js-snclient.md
> +
```suggestion
import { Repository } from "@sensenet/client-core";

const repository = new Repository({
  repositoryUrl: "https://dev.demo.sensenet.com"
});

try {
    const result = await repository.loadCollection({
      path: "/Root/Content/IT",
      oDataOptions: {
        top: 3,
        skip: 4,
        inlineCount: "allpages"
      }
    });
  console.log(result);
} catch (error) {
  console.log(error);
}
```

2020-01-28 14:58 UTC, B3zo0 commented on content/docs/api/examples/entry/byId/js-snclient.md
> +
```suggestion
import { Repository } from "@sensenet/client-core";

const repository = new Repository({
  repositoryUrl: "https://dev.demo.sensenet.com"
});

try {
    const result = await repository.load({
      idOrPath: 1284,
    });
  console.log(result);
} catch (error) {
  console.log(error);
}
```

2020-01-28 15:00 UTC, B3zo0 commented on content/docs/api/examples/entry/byPath/js-snclient.md
> +
```suggestion
import { Repository } from "@sensenet/client-core";

const repository = new Repository({
  repositoryUrl: "https://dev.demo.sensenet.com"
});

try {
    const result = await repository.load({
      idOrPath: 'Root/Content/IT',
    });
  console.log(result);
} catch (error) {
  console.log(error);
}
```

2020-01-29 08:11 UTC, tusmester requested changes

2020-01-29 08:11 UTC, tusmester commented on content/docs/api/examples/collection/children/dotnet.md
> +
```suggestion
await Content.LoadCollectionAsync("/Root/Content");
```

2020-01-29 08:11 UTC, tusmester commented on content/docs/api/examples/collection/count/dotnet.md
> +
```suggestion
await Content.GetCountAsync("/Root/Content", null);
```

2020-01-29 08:11 UTC, tusmester commented on content/docs/api/examples/collection/inlinecount/dotnet.md
> +
```suggestion
var result = await RESTCaller.GetResponseJsonAsync(new ODataRequest
{
    IsCollectionRequest = true,
    Path = "/Root/Content/IT",
    Top = 3,
    Skip = 4,
    Parameters = { { "$inlinecount", "allpages" } }
});
```

2020-01-29 08:11 UTC, tusmester commented on content/docs/api/examples/entry/propertyValue/dotnet.md
> +
```suggestion
await RESTCaller.GetResponseStringAsync(new Uri("https://dev.demo.sensenet.com/OData.svc/Root/Content/('IT')/DisplayName/$value"));
```

2020-01-29 08:49 UTC, merged