Tutorial/sn client js jwt
SenseNet/sensenet.github.io pull request #43
Opened 2017-05-19 13:49 UTC by gallayl

Added tutorial: **JWT Authentication in sn-client-js**

2017-05-19 14:02 UTC, iviczl commented
In the first sentence there is a strange word: "whitch"

2017-05-19 14:48 UTC, iviczl commented on _docs/tutorials/how-to-use-jwt-in-sn-client-js.md
> +JWT Authentication is available only with HTTPS connection. To continue with IIS Express, you can press F4 on the Web project to enable SSL and check the **https URL**.
JWT authentication is available only through HTTPS connection. To set it for IIS Express, press F4 on the web project to the Properties page and enable SSL. After that you can check the generated HTTPS URL.

2017-05-19 14:49 UTC, iviczl commented on _docs/tutorials/how-to-use-jwt-in-sn-client-js.md
> +To avoid CORS issues, we will use a Http Proxy middleware to redirect OData and Session Management requests from our development server to our preinstalled sense NET site. To do that, we have to inst
sensenet ECM site

2017-05-19 14:52 UTC, iviczl commented on _docs/tutorials/how-to-use-jwt-in-sn-client-js.md
> +On the Authentitcation Service instance, you can access the followings:
On the Authentication Service instance, you can access the following features:

2017-06-01 10:43 UTC, borsi requested changes
Cool 👍 
I found some minor grammatical errors, but otherwise it runs smooth.

2017-06-01 10:43 UTC, borsi commented on _docs/tutorials/how-to-use-jwt-in-sn-client-js.md
> +          "target": "https://sn-local/",    // This should point to your sensenet ECM site. Please also note that is has to be use HTTPS
it has to use HTTPS

2017-06-01 10:43 UTC, borsi commented on _docs/tutorials/how-to-use-jwt-in-sn-client-js.md
> +We can continue with [authenticate our routing](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/securing-your-app/2). It's a common scenario to make frontend routes only available to
Grammar:
> [...] authenticat**ing** our routing [...]

2017-06-01 10:43 UTC, borsi commented on _docs/tutorials/how-to-use-jwt-in-sn-client-js.md
> +```xml
It might be obvious for some, but you have to add this section in the configSections as well. Right?
(Because I am not a developer, it was not obvious for me, so I had to google a little)
Or maybe my sensenet version is too old?

2017-06-01 10:43 UTC, borsi commented on _docs/tutorials/how-to-use-jwt-in-sn-client-js.md
> +We've also implemented the **attached** [lifecycle event](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/creating-components/3), this will kick in right after the routes has been co
Grammar
> [...] after the routes have been configured [...]

2017-06-01 12:09 UTC, gallayl commented on _docs/tutorials/how-to-use-jwt-in-sn-client-js.md
> +```xml
This section should be added automatically when using Sensenet.Services >=7.0.0-beta2 with an empty *SymmetricKeySecret* value

2017-06-01 12:09 UTC, gallayl commented on _docs/tutorials/how-to-use-jwt-in-sn-client-js.md
> +          "target": "https://sn-local/",    // This should point to your sensenet ECM site. Please also note that is has to be use HTTPS
ok

2017-06-01 12:10 UTC, gallayl commented on _docs/tutorials/how-to-use-jwt-in-sn-client-js.md
> +We can continue with [authenticate our routing](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/securing-your-app/2). It's a common scenario to make frontend routes only available to
ok

2017-06-01 12:12 UTC, gallayl commented on _docs/tutorials/how-to-use-jwt-in-sn-client-js.md
> +We've also implemented the **attached** [lifecycle event](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/creating-components/3), this will kick in right after the routes has been co
ok

2017-06-01 13:05 UTC, borsi approved these changes

2017-06-01 15:09 UTC, merged