Updates/2020-11
SenseNet/sensenet.github.io pull request #466
Opened 2020-11-19 10:28 UTC by pusztaienike

2020-11-20 14:25 UTC, taki9 commented on _updates/2020-11-23-november.md
> +- Some error messages were not handled correctly on group membership dialog, not it is fixed. 💬 [#1080](https://github.com/SenseNet/sn-client/pull/1080)
```suggestion
- Some error messages were not handled correctly on group membership dialog, now it is fixed. 💬 [#1080](https://github.com/SenseNet/sn-client/pull/1080)
```

2020-11-20 14:25 UTC, taki9 commented on _updates/2020-11-23-november.md
> +- You can use now reference fields on you custom menuitem. ⏬ [#1021](https://github.com/SenseNet/sn-client/pull/1021)
```suggestion
- You can use now reference fields on your custom menuitem. ⏬ [#1021](https://github.com/SenseNet/sn-client/pull/1021)
```

2020-11-20 14:25 UTC, taki9 commented on _updates/2020-11-23-november.md
> +```
```suggestion
```typescript
```

2020-11-20 14:25 UTC, taki9 commented on _updates/2020-11-23-november.md
> +```
```suggestion
```typescript
```

2020-11-23 08:50 UTC, herflis requested changes

2020-11-23 08:50 UTC, herflis commented on _updates/2020-11-23-november.md
> +We also fixed bugs as usual, bugfixes never end. 🐛
```suggestion
We also fixed bugs as usual, bugfixing never ends. 🐛
```

2020-11-23 08:50 UTC, herflis commented on _updates/2020-11-23-november.md
> +- There were some components which did not follow the the font-size-change of google chrome. Now this is fixed, you can use sensenet with large or extra large font-sizes as well. 👓 [#1075](https://gi
```suggestion
- There were some components which did not follow the font-size-change of google chrome. Now this is fixed, you can use sensenet with large or extra large font-sizes as well. 👓 [#1075](https://github.com/SenseNet/sn-client/pull/1075)
```

2020-11-23 08:50 UTC, herflis commented on _updates/2020-11-23-november.md
> +- A notification problem was also noticed during query writing which has since been resolved. ⚠️ [#1081](https://github.com/SenseNet/sn-client/pull/1081)
```suggestion
- A notification problem was also noticed during query writing which has been resolved. ⚠️ [#1081](https://github.com/SenseNet/sn-client/pull/1081)
```

2020-11-23 08:50 UTC, herflis commented on _updates/2020-11-23-november.md
> +- You can use now reference fields on your custom menuitem. ⏬ [#1021](https://github.com/SenseNet/sn-client/pull/1021)
```suggestion
- You can use now reference fields in your custom menuitems. ⏬ [#1021](https://github.com/SenseNet/sn-client/pull/1021)
```

2020-11-23 08:50 UTC, herflis commented on _updates/2020-11-23-november.md
> +- New function has added to SchemaStore [#2021](https://github.com/SenseNet/sn-client/pull/1021)
```suggestion
- New function is added to SchemaStore [#2021](https://github.com/SenseNet/sn-client/pull/1021)
```

2020-11-23 08:50 UTC, herflis commented on _updates/2020-11-23-november.md
> +- New optional prop has added to virtualized-table:
```suggestion
- New optional prop is added to virtualized-table:
```

2020-11-23 13:53 UTC, merged