Add post about collaboration with sensenet
SenseNet/sensenet.github.io pull request #485
Opened 2021-03-09 09:22 UTC by herflis

2021-03-09 10:45 UTC, huszerlbence requested changes
gg

made some small changes, please check them and approve if you agree.

2021-03-09 10:45 UTC, huszerlbence commented on _posts/2021-03-10-5-ways-to-unlock-true-collaboration-with-a-headless-cms.md
> +Basic building blocks of a collaborative content management process are the different states of content aka. [versions in terms of sensenet](https://docs.sensenet.com/concepts/collaboration/01-versio
```suggestion
Basic building blocks of a collaborative content management process are the different states of content aka. [versions in terms of sensenet](https://docs.sensenet.com/concepts/collaboration/01-versioning). The whole lifecycle of a content from the first draft till the final public version can be tracked using version numbers.  Set versioning and approval on a container and your team will be able to follow if a content should be reviewed, corrected or approved both on the admin surface and with the API.
```

2021-03-09 10:45 UTC, huszerlbence commented on _posts/2021-03-10-5-ways-to-unlock-true-collaboration-with-a-headless-cms.md
> +[Document preview feature](https://docs.sensenet.com/concepts/document-previews) of sensenet is a useful teamwork tool in itself letting you upload your docs and share them with people who don't have
```suggestion
[Document preview feature](https://docs.sensenet.com/concepts/document-previews) of sensenet is a useful teamwork tool in itself letting you upload your docs and share them with people who don't have the tools to open them. To make it more powerful we have added the possibility to comment any part of the preview images. This way you could even discuss the design plans with the customer, moving the whole project and all the related content to the same hub.
```

2021-03-09 10:45 UTC, huszerlbence commented on _posts/2021-03-10-5-ways-to-unlock-true-collaboration-with-a-headless-cms.md
> +Why you would use different tools for each work phase when you can write, review, discuss and correct docs directly in the browser? [Office Online editing](https://docs.sensenet.com/concepts/collabor
```suggestion
Why would you use different tools for each work phase when you can write, review, discuss and correct docs directly in the browser? [Office Online editing](https://docs.sensenet.com/concepts/collaboration/03-office-online-editing) is integrated to sensenet making it possible to collaborate on documents as you are used to on your own desktop computer or in google docs. 
```

2021-03-10 08:02 UTC, molnarm84 commented on _posts/2021-03-10-6-ways-to-unlock-true-collaboration-with-a-headless-cms.md
> +With sensenet you can invite your teammates or customers to share content with them, no matter how far they are from you at the moment. Registered users or groups can join you to work on the same con
```suggestion
With sensenet you can invite your teammates or customers to share content with them, no matter how far they are from you at the moment. Registered users or groups can join you to work on the same content on various levels (view, edit) and you can share link of a content with external users let them, review it or even work together without them having to register. Work together remotely like pros, give your projects a collaborative boost with [content sharing](https://docs.sensenet.com/concepts/collaboration/06-sharing)!
```

2021-03-10 09:07 UTC, merged